//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemsParser.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TemsParser.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элемент с таким именем уже содержится в списке..
        /// </summary>
        internal static string ElementAlreadyContained {
            get {
                return ResourceManager.GetString("ElementAlreadyContained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл не найден..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле технологии freqColumnName должно быть заполнено..
        /// </summary>
        internal static string FreqColumnNamePartRequired {
            get {
                return ResourceManager.GetString("FreqColumnNamePartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список частот должен быть заполнен..
        /// </summary>
        internal static string FreqValuesRequired {
            get {
                return ResourceManager.GetString("FreqValuesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле технологии latitudeColumnName должно быть заполнено..
        /// </summary>
        internal static string LatitudeColumnNameRequired {
            get {
                return ResourceManager.GetString("LatitudeColumnNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле технологии levelColumnName должно быть заполнено..
        /// </summary>
        internal static string LevelColumnNamePartRequired {
            get {
                return ResourceManager.GetString("LevelColumnNamePartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле технологии longitudeColumnName должно быть заполнено..
        /// </summary>
        internal static string LongitudeColumnNameRequired {
            get {
                return ResourceManager.GetString("LongitudeColumnNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование должно содержать не более 16 символов..
        /// </summary>
        internal static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование должно состоять только из цифр, букв и пробелов..
        /// </summary>
        internal static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет выбранных файлов..
        /// </summary>
        internal static string NoSelectedFiles {
            get {
                return ResourceManager.GetString("NoSelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование оператора должно содержать не более 16 символов..
        /// </summary>
        internal static string OperatorNameMaxLength {
            get {
                return ResourceManager.GetString("OperatorNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Названия оператора нет в списке. Добавьте имя оператора в список operatorsList..
        /// </summary>
        internal static string OperatorNameNotListed {
            get {
                return ResourceManager.GetString("OperatorNameNotListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название оператора должно быть заполнено..
        /// </summary>
        internal static string OperatorNameRequired {
            get {
                return ResourceManager.GetString("OperatorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование оператора должно состоять только из цифр, букв и пробелов..
        /// </summary>
        internal static string OperatorNames {
            get {
                return ResourceManager.GetString("OperatorNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбрано ни одного оператора..
        /// </summary>
        internal static string OperatorNotSelected {
            get {
                return ResourceManager.GetString("OperatorNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование региона должно содержать не более 16 символов..
        /// </summary>
        internal static string RegionNameMaxLength {
            get {
                return ResourceManager.GetString("RegionNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Названия региона нет в списке. Добавьте имя региона в список regionsList..
        /// </summary>
        internal static string RegionNameNotListed {
            get {
                return ResourceManager.GetString("RegionNameNotListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название региона должно быть заполнено..
        /// </summary>
        internal static string RegionNameRequired {
            get {
                return ResourceManager.GetString("RegionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование региона должно состоять только из цифр, букв и пробелов..
        /// </summary>
        internal static string RegionNames {
            get {
                return ResourceManager.GetString("RegionNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обязательно для заполнения..
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование технологии должно содержать не более 16 символов..
        /// </summary>
        internal static string TechNameMaxLength {
            get {
                return ResourceManager.GetString("TechNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование технологии должно состоять только из цифр, букв и пробелов..
        /// </summary>
        internal static string TechNames {
            get {
                return ResourceManager.GetString("TechNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Названия технологии нет в списке. Добавьте имя технологии в список technologiesList..
        /// </summary>
        internal static string TechnologyNameNotListed {
            get {
                return ResourceManager.GetString("TechnologyNameNotListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название технологии должно быть заполнено..
        /// </summary>
        internal static string TechnologyNameRequired {
            get {
                return ResourceManager.GetString("TechnologyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбрано ни одной технологии..
        /// </summary>
        internal static string TechnologyNotSelected {
            get {
                return ResourceManager.GetString("TechnologyNotSelected", resourceCulture);
            }
        }
    }
}
